### ISSUE TITLE
Links to module specs

### ISSUE THREAD

**Issue by toteki** [umee-network/docs#5]
Module specs in `umee-network/umee` can be linked from a list in the readme. Folder paths follow the pattern `x/leverage/spec/` for `leverage`, `oracle`, and later `incentive`.

Links to ADRs could be provided too, though those need a bit of cleanup to not be redundant with specs.

**Comment by brandoncomer** [comment]
@toteki do we need those in the spec folder or can we consolidate all docs into this repo? if we still need spec folder I'll just link it

**Comment by toteki** [comment]
Spec folder seems to be conventional for cosmos modules (examples: [sdk](https://github.com/cosmos/cosmos-sdk/tree/main/x/bank), [osmosis](https://github.com/osmosis-labs/osmosis/tree/main/x/mint)) so best to link them here.
